version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: drupal
            MYSQL_USER: drupal
            MYSQL_PASSWORD: drupal
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        build: ./php
        expose:
            - "9000"
        volumes:
            - ./:/var/www/drupal
        links:
            - db:mysql
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
